### PR TITLE
Only set tasks = true when parsing plans.

### LINKED ISSUE #251: class with "apply" attribute causes parser error
## Describe the Bug
On a manifest that contains the following code:
```
reboot { 'Patching as Code - Patch Reboot':
  apply    => 'immediately',
  schedule => 'Patching as Code - Patch Window'
}
```
The puppet strings parser errors out with
```
[error]: Failed to parse manifests/init.pp: Syntax error at 'apply' (line: 173, column: 3)
```
If the specific line with `apply =>` gets commented out, the parser succeeds.

## Expected Behavior
The strings parser should not handle occurrences of the term `apply` as a special case, if they are attributes of classes.

## Steps to Reproduce
1. Create a valid puppet manifest
2. Add a resource that contains an attribute named `apply`
3. Run `puppet parser validate` to confirm the manifest is valid
4. Run `puppet strings generate`
5. Notice the parser chokes on the `apply` attribute.

## Environment
 - PE 2019.8.0
 - Client: MacOS, Puppet Agent 6.0.2, puppet-strings 2.4.0, yard 0.9.24

### PR DESCRIPTION
**Pull request by binford2k**
Only set tasks = true when parsing plans. The tests fail because the tested pathname is not the same pattern, so the regex fails. Do you have suggestions @scotje?

Fixes #251

### CODE REVIEW

File: lib/puppet-strings/yard/parsers/puppet/parser.rb [hunk 1]
```diff
@@ -22,10 +22,12 @@ def initialize(source, filename)
   # @return [void]
   def parse
     begin
-      Puppet[:tasks] = true if Puppet.settings.include?(:tasks)
-      if Puppet::Util::Package.versioncmp(Puppet.version, "5.0.0") < 0 && @file.to_s.match(/^plans\//)
-        log.warn "Skipping #{@file}: Puppet Plans require Puppet 5 or greater."
-        return
+      if @file.to_s.match(/^plans\//)
```
Comment (binford2k) [inline lib/puppet-strings/yard/parsers/puppet/parser.rb:25]: @scotje this regex fails during testing because it's in the full fixtures directory. If I remove the start-of-string anchor, tests pass, but that's probably not a good solution. Any other ideas?

Comment (scotje) [reply lib/puppet-strings/yard/parsers/puppet/parser.rb:25]: We should probably extract this test into a helper method and then we can stub that out in the tests

**Comment by pmcmaw** [comment]
Hey @binford2k just wondering if this is still functionality you are still interested in working on?

**Comment by binford2k** [comment]
@pmcmaw I'll finish it up next week after kickoff

**Comment by da-ar** [comment]
Hello @binford2k, there's probably a little more required now to get the PR across the line. What would you like to do?

File: lib/puppet-strings/yard/parsers/puppet/parser.rb (hunk 1 above)
Comment (da-ar) [inline lib/puppet-strings/yard/parsers/puppet/parser.rb:25]: Would this work well enough? Original use case is there to only match `plans/` but an additional check for `/plans/` matches for the test without, i believe, hitting any accidental matches for something that isnt a plan?

```suggestion
      if @file.to_s.match(/[^plans|\/plans]\//)
```
